### PR TITLE
Updated some zh-cn localizations

### PR DESCRIPTION
**Pull request by Snoopy1866**
Correct some zh-cn translations for the word "Comprehension"

"理解" is the not suitable translation for the word "Comprehension" in term of programming, "推导式" is much better.

### CODE REVIEW

**Comment by erictraut** [comment]
Pyright's localized strings come from the Microsoft Pylance team. Any changes made in the pyright code base would be overwritten the next time Pylance syncs with pyright.

@rchiodo, @debonte, could you see if the Pylance localization team would like to incorporate these suggested changes?

**Comment by debonte** [comment]
@Snoopy1866, thanks for the contribution! Comprehension is definitely a tough word to translate. I'll submit this as a bug to our localization team and see what they think. I'll follow up here once we hear back from them.

**Comment by debonte** [comment]
For reference, here is the loc issue I filed (only available internally) -- https://dev.azure.com/ceapex/CEINTL/_workitems/edit/1001711

**Comment by debonte** [comment]
@Snoopy1866, your suggestions were accepted and I just [merged](https://github.com/microsoft/pyright/pull/9133) them into Pyright. They'll be included in the next release. Thanks again!

**Pull request closed without merging**
