### PR TITLE
Add __future__ module as import suggestion

### PR DESCRIPTION
**Pull request by cdce8p**
See: https://github.com/microsoft/pylance-release/issues/539

### CODE REVIEW

**Comment by jakebailey** [comment]
Please don't add "fixes" to the PR description for the linked issues; we only close issues once the code is actually released (to better indicate when it's actually available) and GitHub will auto-close them.

**Comment by erictraut** [comment]
This change looks good to me, but a unit test should be added for it.

**Comment by cdce8p** [comment]
I've added a unit test

**Comment by erictraut** [comment]
Thanks for the contribution. Merging.

**Pull request merged**
