### PR TITLE
fix: reportMissingModuleSource default none

### PR DESCRIPTION
**Pull request by fannheyward**
schema default is none https://github.com/microsoft/pyright/blob/58a349b50e5212d29ab1606f8f3cb8b6557c7aa5/packages/vscode-pyright/schemas/pyrightconfig.schema.json#L138-L142

### CODE REVIEW

**Comment by erictraut** [comment]
This isn't correct. If you don't specify reportMissingModuleSource, it will default to "warning".

**Comment by fannheyward** [comment]
Did I missed something? As schema defined, `reportMissingModuleSource`'s default is none, but in `python.analysis.diagnosticSeverityOverrides`, default is warning.

Others, for example `reportInvalidStubStatement`'s default are same in both schema and python.analysis.diagnosticSeverityOverrides properties.

**Comment by erictraut** [comment]
You are correct that there's a bug here, but it's in the schema. Both of them should be "warning".

Here's the table in the source code that specifies the default values when "typeCheckingMode" is "off": https://github.com/microsoft/pyright/blob/7fd612ad703f04d0f6133e8820c705a91f3bb9ca/packages/pyright-internal/src/common/configOptions.ts#L277

And here's the table that specifies the default values when "typeCheckingMode" is "basic": https://github.com/microsoft/pyright/blob/7fd612ad703f04d0f6133e8820c705a91f3bb9ca/packages/pyright-internal/src/common/configOptions.ts#L332

It's not clear which of these tables should be reflected in the JSON schema and the package.json diagnosticSeverityOverrides properties. I opted to reflect the type checking mode "off" setting because that's the default type checking mode for Pylance, and I wanted the Pyright defaults to be consistent with Pylance.

**Comment by erictraut** [comment]
I just pushed a fix to the schema. Thanks for pointing out the inconsistency.

**Pull request closed without merging**
