### PR TITLE
Restrict vscode-pyright document selector to `file` and `untitled` schemes

### PR DESCRIPTION
**Pull request by debonte**
Address https://github.com/microsoft/pyright/issues/7215

This will prevent VS Code from communicating with Pyright about Python documents with URI schemes other than `file` and `untitled`. For example: `vscode-notebook-cell`.

I considered filtering out notebook cells in the textDocument didOpen, didChange, and didClose handlers, but then VS Code will still send requests (ex. hover) for the filtered out documents. So it seems best to tell VS Code more clearly what Pyright can handle.

This matches Pylance's document selector minus notebooks and virtual file systems. Pyright doesn't support virtual file systems, right?

### CODE REVIEW

**Review by rchiodo — APPROVED** [review]

**Comment by erictraut** [comment]
I have some concerns about this approach. I think I recall that some editors use a URI other than "untitled" for unsaved documents. This would break those clients.

Perhaps we could blacklist notebooks rather than whitelisting just a few specific url types?

**Comment by rchiodo** [comment]
> Pyright doesn't support virtual file systems, right?

No, it does not. It would need a way to send a request to read to a client. (The sync server support)

**Comment by debonte** [comment]
> I think I recall that some editors use a URI other than "untitled" for unsaved documents. This would break those clients.

This change is in `vscode-pyright`. I was assuming that other editors would not use that package at all. Is that not true?

**Review by erictraut — APPROVED** [review]

**Comment by erictraut** [comment]
> This change is in vscode-pyright. I was assuming that other editors would not use that package at all. Is that not true?

That should be fine then. Thanks.

**Pull request merged**
