### PR TITLE
added code coverage on CI.

### PR DESCRIPTION
**Pull request by heejaechang**
code coverage info should be published to CI now.

### CODE REVIEW

**Comment by heejaechang** [comment]
tagging @jakebailey @RaymonGulati1

**Comment by jakebailey** [comment]
Note that the actual pipeline needs updating to read the files produced here, so you won't see them immediately. Working on that.

**Comment by heejaechang** [comment]
seems azure pipeline is working against us today. I ran it manually on my dev box and verified build and tests working.

**Pull request merged**
