### PR TITLE
Add logging for TypeAnalyzer._applyDecorator

### PR DESCRIPTION
**Pull request by ChrisLinn**

### CODE REVIEW

**Comment by erictraut** [comment]
I'm actively working on this code currently. Logging output to the console isn't the right approach here anyway. It should emit diagnostics that appear in VS Code's Problems panel.

**Comment by ChrisLinn** [comment]
u r right

**Comment by ChrisLinn** [comment]
oh just becoz i find  that   we compare `watch` with `undefined` in _server/src/pyright.ts_ and guessed we'd better follow this when it comes to an undefined obj (excluding arrayy, boolean, string...).

**Comment by erictraut** [comment]
That's a different circumstance because `watch` is allowed to be defined as `undefined` or `null`, and it's important to distinguish between these two cases.

**Comment by ChrisLinn** [comment]
thx for ur explanation

**Pull request closed without merging**
