### PR TITLE
npm audit fix

### PR DESCRIPTION
**Pull request by bschnurr**

### CODE REVIEW

**Comment by erictraut** [comment]
Do you want to do this for all of the three sub-projects as well?

**Comment by bschnurr** [comment]
the main concern was with "parse-url": "^6.0.0"
these changes appear to be related to learna

**Review by erictraut — APPROVED** [review]

**Comment by erictraut** [comment]
@bschnurr, do you plan to merge this or abandon it?

**Comment by bschnurr** [comment]
I thought i merged this already sorry

**Pull request merged**
