### PR TITLE
Show file path in verifytypes output

### PR DESCRIPTION
**Pull request by vemel**
## Notes

Issue: somehow related to https://github.com/microsoft/pyright/issues/1395

File paths are relative to be consistent with other reports.

## Changes

Enhancement: `pyright --verifytypes` output shows file path
Enhancement: `pyright --verifytypes` output shows node range
Bugfix: `pyright --verifytypes` JSON output shows correct `file` path
Bugfix: `pyright --verifytypes` JSON output shows correct node `range` in diagnostics

### CODE REVIEW

**Comment by erictraut** [comment]
I'm planning on a general rewrite of the verifytypes functionality soon. I'd prefer not to make this change now because it modifies the output schema, and other users may be relying on the current format. I'd like to make a single large breaking change rather than multiple small breaking change.

I appreciate your contributions, but for efficiency reasons, it would work better if we discussed behavior changes before you submit a PR.

**Comment by vemel** [comment]
Changes to the schema should be fully compatible to existing schema:

- `file` field still remains a string, but now it is not empty if diagnostics message comes from a module
- `range` field has been added and it is consistent with messages generated by `pyright` main mode

Probably, we can keep text output as it was and make changes only to JSON output. I noticed that both text and JSON outputs already had support for `range`.

**Comment by erictraut** [comment]
Ah, I see. You're merging the file-level diagnostics into the common diagnostics at the end. Makes sense. OK, I'll accept this PR. But as I mentioned, this is all likely to get replaced soon.

**Comment by vemel** [comment]
Thank you a lot! I did not split messages to array as the original issue suggested, but I think more JSON-friendly was can be added lated alongside with current `message`.

**Comment by erictraut** [comment]
I've started a new discussion about a rewrite of the verifytypes functionality here: https://github.com/microsoft/pyright/discussions/1568. I'd appreciate any thoughts you have.

**Pull request merged**
