### PR TITLE
`--version` cli argument added to pyright

### PR DESCRIPTION
**Pull request by butuzov**
Enables support of `--version` argument descibed in #117

### CODE REVIEW

**Comment by erictraut** [comment]
Good suggestion. Thanks for the contribution.

**Comment by butuzov** [comment]
Great!

Btw - are `--files` and `--verbose` experimental? (nothing about them in `pyright --help`, only `--verbose` described at `docs/command-line.md`

**Comment by erictraut** [comment]
"files" is implicit. You simply list the individual files with no "--files" switch. 

I forgot to add "--verbose" to the help. I'll fix that.

**Comment by butuzov** [comment]
I have tested already `files` =), it's kinda obvious and its described in the code. 

Thank you!

**Pull request merged**
