### PR TITLE
fix: usage of `deprecated` version of `Node.js`

### LINKED ISSUE #8199: `validation.yml` uses `actions/cache@v3`, which uses a `deprecated` version of `Node.js`

### PR DESCRIPTION
**Pull request by hamirmahal**
fixes #8199.

### CODE REVIEW

**Review by hamirmahal — COMMENTED** [review]
`actions/cache@v4` is the latest major version at the time of this writing.

**Review by debonte — APPROVED** [review]
Thanks @hamirmahal!

**Comment by hamirmahal** [comment]
You're welcome @debonte!

**Comment by debonte** [comment]
@erictraut, is there something wrong with the CLA thing? I see that https://github.com/microsoft/pyright/pull/8186 didn't run the CLA check either.

**Comment by erictraut** [comment]
@debonte, I don't know about the license/cla action. It was added automatically by the team at Microsoft that oversees OSS projects. They may have some insights.

**Comment by erictraut** [comment]
This PR looks OK to me, but I'm not sure what problem this is fixing. I've never seen an issue with our CI scripts relating to the v3 version of this action. The phrase "if it's ain't broken, don't fix it" comes to mind. Is the concern that it will stop working at some point in the future? @hamirmahal, can you explain why you are proposing that we make this change?

**Comment by debonte** [comment]
We update these regularly in pyrx for what it's worth. I'd be inclined to take it, if only to reduce the warning noise on the action summary pages so we can see real issues more easily.

**Comment by hamirmahal** [comment]
@erictraut Like Erik mentioned, updating to `Node 20` will reduce noise and make actual issues more noticeable.

You can sometimes get a speed improvement for free by updating `Node`, and even if GitHub Actions are free for open source repositories, there's still the environmental impact of runners unnecessarily taking a few seconds longer to run by being on an older, slower version of `Node`. If there is a speed improvement, developers also benefit by getting feedback on their changes more quickly.

[GitHub recommends Actions users use the latest versions](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/). [Node 16 has reached its end of life](https://github.com/nodejs/Release/#end-of-life-releases).

**Pull request merged**
