### PR TITLE
[WIP] Adding support for generic TypedDicts

### PR DESCRIPTION
**Pull request by sransara**
Hi, what do you think about supporting generic TypedDicts?

In this pull request I tried to add this functionality hopefully without mangling too many other things.
The basis of the implementation is by enhancing the `getTypedDictMembersForClass` and `getTypedDictMembersForClassRecursive`.

There is also a [mypy issue](https://github.com/python/mypy/issues/3863) on adding support for generic TypedDicts.

In the following code you can see this PR in action, but there are still a few actions TODO items. I just wanted to get some feedback before moving forward.

```python
from typing import TypedDict, TypeVar, Generic, List
T = TypeVar("T")

class TD(Generic[T], TypedDict):
    f1: List[T]
    
def test_td(aa: TD[T], bb: TD[T]):
    return aa["f1"], bb["f1"]

td1 = test_td({"f1": ["foo"]}, {"f1": ["bar"]})
reveal_type(td1) # info: Type of "td1" is "tuple[List[str], List[str]]"

test_td({"f1": ["foo"]}, {"f1": [1]}) # error

class TD2(TD[T]):
    f2: T

td21: TD2[str] = {
    'f1':["far"],
    'f2':"boo"
}
reveal_type(td21["f1"]) # info: Type of "td21["f1"]" is "List[str]"

td22 = TD2(
    f1=["far"],
    f2="boo"
)
reveal_type(td22) # info: Type of "td22" is "TD2[str]"

td23: TD2[str] = {
    'f1':[0],
    'f2':"boo"
} # error

td24: TD2[str] = TD2(
    f1=[0],
    f2="boo"
) # error

td25 = TD2(
    f1=[0],
    f2="boo"
) 
reveal_type(td25) #  info: Type of "td25" is "TD2[int | Literal['boo']]
```

_TODO_
- [ ]  Support for declaring with TypedDict constructor notation
- [ ]  Adding proper test cases to the automated test suite
- [ ]  And never enough testing to make sure no corner cases were missed

### CODE REVIEW

**Comment by erictraut** [comment]
Generic TypedDict is not supported by PEP 589, nor is it supported at runtime by Python.

If you want this to be supported, you'd need to go through the typing-sig or PEP drafting process.

We are not interested in adding support to Pyright unless/until it becomes part of the Python type standard.

**Comment by erictraut** [comment]
That said, I'm impressed that you were able to add this functionality!

**Comment by sransara** [comment]
> Generic TypedDict is not supported by PEP 589, nor is it supported at runtime by Python.
>
> If you want this to be supported, you'd need to go through the typing-sig or PEP drafting process.
> 
> We are not interested in adding support to Pyright unless/until it becomes part of the Python type standard.

Oh that is sad. I can take a look at how to suggest it on typing-sig mailing list. Should I close this PR until something is certain?

> That said, I'm impressed that you were able to add this functionality!

It was a fun exercise :)

**Comment by erictraut** [comment]
Yeah, please close this PR for now. If it is added to the Python 3.10 runtime, we can revive this PR.

**Comment by sransara** [comment]
Sounds good. Thanks for the quick response.

**Comment by jakebailey** [comment]
RE: typing-sig, if you haven't done it before, easiest is to just sign up on mail.python.org and send emails there to the typing-sig asking about the feature; I'd expect that either the PEP can be revised to be less lax, or that it will end up needing a new PEP thanks to the aforementioned runtime type changes (thanks to needing the square brackets to work at runtime, etc).

**Comment by sransara** [comment]
Got it. Thank you for the information.

**Comment by sransara** [comment]
I sent out the email to typing-sig mailing list (awaiting moderator approval at the moment). Fingers crossed hoping there's a way to move forward with the runtime support.

**Pull request closed without merging**
