### PR TITLE
feat: ignoreSync

### PR DESCRIPTION
**Pull request by Malix-Labs**

### CODE REVIEW

**Comment by Malix-Labs** [comment]
@erictraut why ?

Also, it was a draft PR

**Comment by erictraut** [comment]
@Malix-Labs, I assumed this PR was created in error. There was no context about what it was attempting to do, and its contents didn't make sense to me. I presume that your intent was to check in a change to your own fork but not create a PR to the main pyright fork.

If you're interested in suggesting a new feature in pyright, I recommend that you start by posting an enhancement request and/or a discussion topic to get feedback on the feature.

**Comment by Malix-Labs** [comment]
> If you're interested in suggesting a new feature in pyright, I recommend that you start by posting an enhancement request and/or a discussion topic to get feedback on the feature.

Right, I will open an issue and link it to that PR first, thanks !

**Comment by Malix-Labs** [comment]
I couldn't find the difference between `ignoreSync` and the "machine" scope, so I will first wait for vscode's clarification (see https://github.com/microsoft/vscode-docs/issues/7638)

Consider as draft (not ready for review)

**Pull request closed without merging**
