### PR TITLE
recommend pylance over pyright for vs code

### PR DESCRIPTION
**Pull request by jli**

### CODE REVIEW

**Comment by jakebailey** [comment]
I think some aspect of this is covered, if you hadn't seen it: https://github.com/microsoft/pyright#using-pyright-with-vs-code-python-extension

**Comment by erictraut** [comment]
Thanks for the suggestion. I've updated the README to include the gist of your changes, but I reworded it to add more clarity.

**Comment by jli** [comment]
Thanks for the update Eric!

Noticed a small typo:
> For most VS Code users, we recommend using the Pylance extension **rathern** than Pyright.

**Comment by erictraut** [comment]
Good catch. Just fixed. I forgot that I had temporarily disabled the spell-checker extension in VS Code.

**Pull request closed without merging**
