### PR TITLE
improved doc string and more style changes

### PR DESCRIPTION
**Pull request by heejaechang**
this includes changes from @huguesv on doc string improvement and style fix up from @jakebailey

### CODE REVIEW

**Comment by heejaechang** [comment]
@erictraut already signed off. this is to check CI

**Comment by heejaechang** [comment]
wrong changes are included in the PR.

**Comment by jakebailey** [comment]
Apologies if the quotations were the issue with the markdown formatting in the original reformat PR; Prettier did not change those, I did them by hand.

**Comment by erictraut** [comment]
Ah, I assumed it was prettier.

**Comment by heejaechang** [comment]
@jakebailey I get this error
...

D:\dd\pyright\server\src\analyzer\docStringToMarkdown.ts
  53:50  error  Unnecessary escape character: \[  no-useless-escape

✖ 1 problem (1 error, 0 warnings)
...

which I didn't see from the original repo/branch. some setting issue?

**Comment by heejaechang** [comment]
@erictraut are you still blocking the PR? can you let me know what you want for me to change?

**Pull request merged**
