### PR TITLE
Declare workspaceFolders support in server capabilities

### PR DESCRIPTION
**Pull request by the-mikedavis**
The `vscode-languageserver-node` dependency will attempt dynamic capability registration for workspace folder change notifications if this `workspace.workspaceFolders.changeNotifications` is not set in the `InitializeResult`. That is problematic for clients that don't support dynamic capability registration: if we send a JSONRPC error, the server will exit because of the rejected promise.

The server has support for workspace folders and requests and uses change notifications as far as I can see, so I believe it's more correct to declare support for these up-front anyways.

This is the recommended way to avoid dynamic capability registration for this case with `vscode-languageserver-node`: [(comment)](https://github.com/microsoft/vscode-languageserver-node/issues/713#issuecomment-754551117)

Fixes https://github.com/microsoft/pyright/issues/2690
Fixes https://github.com/microsoft/pyright/issues/1302
This and a change within Helix (https://github.com/helix-editor/helix/pull/6058) will resolve issues we started seeing in 1.1.293 (https://github.com/microsoft/pyright/discussions/4602)
See also https://github.com/microsoft/vscode-languageserver-node/commit/5bc82ac3c1c656aa70615c9e3e065fa04e41506e
Revelant part of the spec: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_workspaceFolders
[Here](https://github.com/microsoft/pyright/blob/d22850b041edbc747ec043553a23bdbff55696d6/packages/pyright-internal/src/languageServerBase.ts#L772-L786) is where the change notification handler is set up in pyright and what triggers dynamic capability registration within vscode-languageserver-node.

### CODE REVIEW

**Comment by erictraut** [comment]
Thanks for the contribution. Looks good to me.

@heejaechang, I'm adding you as a reviewer also.

**Review by erictraut — APPROVED** [review]

**Comment by erictraut** [comment]
@heejaechang, any thoughts on this PR? If I don't hear from you in the next day, I'll assume it's OK and merge it.

**Review by heejaechang — APPROVED** [review]

**Comment by heejaechang** [comment]
I think it is right thing to do. we already listen for workspace folder change event and support workspace folders.

**Comment by heejaechang** [comment]
It looks like when we register for workspace folder change event, LSP library automatically send registerCapabilities for workspace folder change support. and that's why it worked fine for vscode and we didn't notice.

**Pull request merged**
