### PR TITLE
Added multi-root workspaceFolder support in path variable expansion

### PR DESCRIPTION
**Pull request by Seairth**
See #7137

### CODE REVIEW

**Comment by Seairth** [comment]
@microsoft-github-policy-service agree

**Comment by Seairth** [comment]
Hmm.  I see that amending the commit reset the PR.  For future reference, what is the preferred approach for addressing issues?

**Comment by Seairth** [comment]
I ran prettier on the files, and it resolved one of the warnings.  I do not know why `npm run check` is reporting a warning about `server.ts`, since running prettier on the file yields no changes.

**Review by rchiodo — APPROVED** [review]
Thanks for adding the workspace:name support. This is great :)

**Comment by Seairth** [comment]
> Thanks for adding the workspace:name support. This is great :)

I'm glad I could contribute back, even if a small way.

**Pull request merged**
